#!/usr/bin/env zsh

if [[ $# -eq 1 ]]; then
    selected=$1
else
    one_depth_dirs=$(find ~/pspace ~/code ~/.config ~/services/modules -maxdepth 1 -mindepth 1 -type d)
    plus_services="$one_depth_dirs \n$(find ~/services -maxdepth 0)"
    selected=$(echo $plus_services | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
